= Tests
[[main-title]]


Running Ansible test is fairly easy if you've installed the prerequisites.

First, start your machine using the `molecule create` command.

Once started, you can deploy your tasks using `molecule converge`

Once converged, you can `molecule verify` executing your tests on the machine.

Finally, `molecule destroy` will kill the VM/Docker container

TIP: Be sure to write your test before implementing so that you can see it failing, so to ensure that you are writing your test the good way !

== Test pipelines

We are using https://github.com/nektos/act[act] in order to test our pipeline.

On any repository, you can execute `act list` to see all the available actions and `act <action>` to trigger it.
You can always update the container used to trigger the tests updating the .actrc file

== Molecule platforms

The prefered molecule platform being docker, it is pretty straightforward to use and test.
For some other edge case, we are using https://github.com/ansible-community/molecule-vagrant/blob/master/molecule_vagrant/test/scenarios/molecule/multi-node/molecule.yml[molecule-vagrant] (example, to test logical volumes or virtualization)