---
# vars file for datastore

lvm_groups:
  - vgname: noraid
    disks:
      - /dev/sda1
    create: true
    lvmetanames:
      - lvname: docker-thinpool
        size: 20%VG
        opts: "--wipesignatures y"
        create: true
        metadata: noraid/docker-thinpoolmeta
        autoextendtreshold: 80
        autoextendpercent: 20
        filesystem: xfs
        mntp: /var/lib/docker
        mount: true
        mopts: defaults,pquota,gquota,quota
      - lvname: docker-thinpoolmeta
        size: 1%VG
        opts: "--wipesignatures y"
        create: true
manage_lvm: false # don't want to mess with that...