#!/usr/bin/env bash
cd packer/bento
git checkout master
git pull upstream master
cd ../..

for f in ansible/roles/*; do
    if [[ -d "$f" && $f != "roles/community" ]]; then
        cd $f
        git checkout master
        git pull upstream master
        cd ../../..
    fi
done


for f in ansible/roles/*; do
    if [[ -d "$f" && $f != "roles/community" ]]; then
        git add $f
        cd ../../..
    fi
done