---
# This is a basic workflow to help you get started with Actions
name: Molecule

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
    branches:
      - master
      - tags/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: install lint prerequisite
      run: |
        sudo apt -y install python3-setuptools ansible-lint

    - name: lint ansible
      run: |
        ansible-lint . --exclude meta
  requirements:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: install prereq
      run: |
        ./configure

  molecule:

    runs-on: ubuntu-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Install molecule
      run: |
        sudo apt update
        sudo apt -y install python3-setuptools python3 python3-pip docker
        sudo pip3 install wheel
        sudo pip3 install docker molecule testinfra

    - name: create molecule vm
      run: |
        molecule create

    - name: install prereq
      run: |
        ./configure

    - name: converge molecule vm
      run: |
        molecule converge

    - name: verify
      run: |
        molecule verify

    - name: teardown
      run: |
        molecule destroy