---
lvm_groups:
  - vgname: noraid
    disks:
      - /dev/sda1
    create: true
    lvmetanames:
      - lvname: kube-share
        size: 100g
        create: True
        expose_nfs: True
        filesystem: xfs
        mntp: /var/shared
        mount: True
        mopts: defaults
      - lvname: docker-thinpool
        size: 100g
        opts: "--wipesignatures y"
        create: True
        metadata: noraid/docker-thinpoolmeta
        autoextendtreshold: 80
        autoextendpercent: 20
        filesystem: xfs
        mntp: /var/lib/docker
        mount: True
        mopts: defaults,pquota,gquota,quota
      - lvname: docker-thinpoolmeta
        size: 1%VG
        opts: "--wipesignatures y"
        create: True
configure_nfs: True
datastore_firewall_zone: libvirt # because nfs is mounted for virtual machines
manage_lvm: False
# reset_ipa_client: Yes
