---
lvm_groups:
  - vgname: noraid
    disks:
      - /dev/sda1
    create: true
    lvmetanames:
      - lvname: kube-share
        size: 100g
        create: true
        expose_nfs: True
        filesystem: xfs
        mntp: /var/shared
        mount: true
        mopts: defaults
      - lvname: docker-thinpool
        size: 100g
        opts: "--wipesignatures y"
        create: true
        metadata: noraid/docker-thinpoolmeta
        autoextendtreshold: 80
        autoextendpercent: 20
        filesystem: xfs
        mntp: /var/lib/docker
        mount: true
        mopts: defaults,pquota,gquota,quota
      - lvname: docker-thinpoolmeta
        size: 1%VG
        opts: "--wipesignatures y"
        create: true
configure_nfs: True
datastore_firewall_zone: libvirt
manage_lvm: False
