---
libvirt_host_pools:
  - name: default # TODO remove this parameter: only 'dir' with /var/lib/libvirt/images works with virt_guest actually
    type: dir
    path: /var/lib/libvirt/images
    mode: 751
    owner: qemu
    group: qemu
libvirt_host_networks:
  - name: default
    mode: nat
    zone: 'libvirt'
    bridge: virbr0
    ip: 192.168.122.1
    netmask: 255.255.255.0
    dhcp_start: 192.168.122.100
    dhcp_end: 192.168.122.200
local_systemusers_user_list:
  - name: libvirt
    group: libvirt
    groups: wheel
virtualization_guest_boxes:
  - name: 'idm.internal.osgiliath.net'
    url: https://app.vagrantup.com/fedora/boxes/34-cloud-base/versions/34.20210423.0/providers/libvirt.box
    memory_mb: 4072
    vcpus: 3
    ssh_port_on_host: 24022
    recreate_machine: False
    ansible_groups:
      - ipaservers
    interfaces:
      - network: default
  - name: 'master.internal.osgiliath.net'
    url: https://app.vagrantup.com/fedora/boxes/34-cloud-base/versions/34.20210423.0/providers/libvirt.box
    memory_mb: 2072
    vcpus: 2
    ssh_port_on_host: 22022
    ansible_groups:
      - kube_master
      - ipaclients
    recreate_machine: true
    interfaces:
      - network: default
  - name: 'node1.internal.osgiliath.net'
    url: https://app.vagrantup.com/fedora/boxes/34-cloud-base/versions/34.20210423.0/providers/libvirt.box
    memory_mb: 3072
    vcpus: 2
    ssh_port_on_host: 23022
    recreate_machine: true
# same as the one in molecule.yml
    ansible_groups:
      - kube_node
      - ipaclients
    interfaces:
      - network: default
