---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    roles-path: ../community
driver:
  name: docker
lint: yamllint . && flake8 && ansible-lint --exclude=meta
platforms:
  - name: ansible-users-vm
    image: fedora:latest
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_ROLES_PATH: ../../..:../../../community
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
