---
# tasks file for ansible-nameserver
- name: ansible-nameserver | check host is in hostfile
  shell: >
    set -o pipefail &&
    cat /etc/hosts | egrep '\s{{ ns_hostname }}\s'
  register: hostnamedeclared
  ignore_errors: true
  changed_when: false

- name: ansible-nameserver | debug hostfile var
  debug:
    var: hostnamedeclared
    verbosity: 3

- name: ansible-orchestration | gather facts on newly created machines
  setup:
  register: masterfacts

- name: ansible-nameserver | add host in hosts file
  lineinfile:
    path: /etc/hosts
    regexp: '^{{ masterfacts.ansible_facts.ansible_default_ipv4.address|default(masterfacts.ansible_facts.ansible_all_ipv4_addresses[0]) }} {{ ns_hostname }}'
    insertbefore: BOF
    line: '{{ masterfacts.ansible_facts.ansible_default_ipv4.address|default(masterfacts.ansible_facts.ansible_all_ipv4_addresses[0]) }} {{ ns_hostname }}'
    owner: root
    group: root
    mode: '0644'
  become: true
  when: >
    hostnamedeclared is failed or
    hostnamedeclared.rc == 1 or
    hostnamedeclared.stdout == 0

- name: ansible-nameserver | add IP6 host in hosts file
  lineinfile:
    path: /etc/hosts
    regexp: '^{{ masterfacts.ansible_facts.ansible_default_ipv6.address|default(masterfacts.ansible_facts.ansible_all_ipv6_addresses[0]) }} {{ ns_hostname }}'
    insertbefore: BOF
    line: '{{ masterfacts.ansible_facts.ansible_default_ipv6.address|default(masterfacts.ansible_facts.ansible_all_ipv6_addresses[0]) }} {{ ns_hostname }}'
    owner: root
    group: root
    mode: '0644'
  become: true
  when: >
    hostnamedeclared is failed or
    hostnamedeclared.rc == 1 or
    hostnamedeclared.stdout == 0

- name: ansible-nameserver | set hostname
  include_role:
    name: tcharl.hostname
  vars:
    hostname: "{{ ns_hostname }}"
    hostname_reboot: false
    ansible_become: true
