---

docker_shared_data: /usr/share/dockerdata
docker_shared_data_nginx_proxy_path: "{{ docker_shared_data }}/nginx"
docker_shared_data_nginx_proxy_certs_path: "{{ docker_shared_data_nginx_proxy_path }}/pki"
docker_shared_data_letsencrypt_path: "{{ docker_shared_data_nginx_proxy_path }}/letsencrypt"
docker_shared_data_nginx_proxy_auth_path: "{{ docker_shared_data_nginx_proxy_path }}/auth"
docker_shared_data_nginx_proxy_vhosts_path: "{{ docker_shared_data_nginx_proxy_path }}/vhost.d"
docker_shared_data_nginx_proxy_html_path: "{{ docker_shared_data_nginx_proxy_path }}/html"
docker_shared_data_registry_path: "{{ docker_shared_data }}/registry"
docker_shared_data_registry_data_path: "{{ docker_shared_data_registry_path }}/data"
docker_shared_data_registry_config_path: "{{ docker_shared_data_registry_path }}/config"
letsencrypt_default_email: "fake@mail.com"
container_registry_domain_name: "containers.dummy.com"
docker_registry_delete_mode: true
docker_registry_readonly_mode: false
docker_registry_users:
  - uid: 'dummyuser'
    pwd: 'password'
gen_certs: true
