---
dependency:
  name: galaxy
  options:
    role-file: ../../meta/main.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: yamllint
platforms:
  - name: Fedora-Molecule-LVM
    box: bento/fedora-31
    box-url: ${platform_root}/packer/bento/builds/fedora-31-x86_64.virtualbox.box
    groups:
      - lvm
    provider_override_args:
      - "persistent_storage.enabled = true"
      - "persistent_storage.location = 'testhdd.vdi'"
      - "persistent_storage.size = 100"
      - "persistent_storage.mount = false"
      - "persistent_storage.diskdevice = '/dev/sdb'"
provisioner:
  name: ansible
  inventory:
    group_vars:
      lvm:
        lvm_groups:
          - vgname: non-persistent
            disks:
              - /dev/sdb1
            create: true
            lvnames:
              - lvname: thinpool
                size: 40%VG
                opts: "--wipesignatures y"
                create: true
                metadata: non-persistent/thinpoolmeta
                autoextendtreshold: 80
                autoextendpercent: 20
              - lvname: thinpoolmeta
                size: 10%VG
                opts: "--wipesignatures y"
                create: true
        manage_lvm: true
  lint: ansible-lint
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
  lint: flake8
