#!/usr/bin/env bash

brew cask install vagrant
brew install ansible
brew install yamllint
brew install flake8
brew install python
brew link --overwrite python
pip install ansible-lint
pip install molecule
pip install 'molecule-vagrant'
pip install paramiko
. configure-virtualbox
