---
- name: Provision store
  hosts: datastore
  roles:
    - role: tcharl.ansible_volumes

- name: Configure and secure host
  hosts: hostmachines
  roles:
    - role: tcharl.ansible_users
    - role: tcharl.ansible_securehost

- name: Provision VMs
  hosts: vmhost
  roles:
    - role: tcharl.ansible_virtualization_guest

- name: Provision Containerization
  hosts: containerization
  roles:
    - role: tcharl.ansible_containerization

...