---
- name: configure hosts
  hosts:
    - all
  roles:
    - role: tcharl.ansible_hostname
    - role: robertdebock.fail2ban
      become: Yes
#    - role: robertdebock.bootstrap
      # TODO should run, but I'm unable to start it again. Comment it if you're not able to, but it can have side effect
#      become: Yes
#      become_method: sudo
#      become_user: root
    - role: robertdebock.epel
    - role: robertdebock.core_dependencies
  become: Yes

- name: install freeipa roles
  hosts:
    - ipaservers
    - ipaclients
  roles:
    - role: tcharl.ansible_securehost

- name: configure datastore nfs enpoints
  hosts:
    - datastore
  roles:
    - role: tcharl.ansible_volumes

- name: install configure freeipa dns for clients
  hosts:
    - ipaclients
  roles:
    - role: tcharl.ansible_nameserver

- name: configure users on server
  hosts:
    - ipaservers
  roles:
    - role: tcharl.ansible_users

- name: install host roles
  hosts: hostmachine1
  roles:
    - role: tcharl.ansible_securehost
    - role: tcharl.ansible_routing
#    - role: ansible-container-registry

- name: configure containerization prereq # Execute master and nodes at the same time: one fact is created by the master and reused by nodes
  hosts: # use this order: master should be created before node
    - kube_master
    - kube_node
    - reverse_proxy
  roles:
    - role: tcharl.ansible_containerization

- name: configure reverse proxy
  hosts: reverse_proxy
  roles:
    - role: tcharl.ansible_routing

- name: configure datastore nfs mountpoints
  hosts:
    - kube_node
  roles:
    - role: tcharl.ansible_volumes

- name: configure kubernetes prereq # Execute master and nodes at the same time: one fact is created by the master and reused by nodes
  hosts:
    - kube_master
    - kube_node
  vars:
    swap_file_state: absent
  roles:
    - role: geerlingguy.swap
  become: Yes

- name: configure kubernetes master # Execute master and nodes at the same time: one fact is created by the master and reused by nodes
  hosts: # use this order: master should be created before node
   - kube_master
  roles:
    - role: tcharl.ansible_orchestration

- name: configure kubernetes nodes
  hosts: # use this order: master should be created before node
   - kube_node
  roles:
    - role: tcharl.ansible_orchestration

...