---
- name: Provision store
  hosts: datastore
  roles:
    - role: tcharl.ansible_volumes

- name: Configure and secure host
  hosts: hostmachines
  roles:
    - role: tcharl.ansible_localuser
    - role: tcharl.fail2ban
    - role: tcharl.ansible_routing

- name: Provision VMs
  hosts: vmhost
  roles:
    - tcharl.ansible_virtualization
    - role: tcharl.ansible_virtualization_guest

- name: Provision Containerization
  hosts: containerization
  roles:
    - role: tcharl.ansible_containerization

...
