---
- name: configure hosts
  hosts:
    - all
  roles:
    - role: robertdebock.epel
      become: Yes
    - role: robertdebock.core_dependencies
      become: Yes
    - role: tcharl.ansible_hostname
      become: Yes
    - role: robertdebock.fail2ban
      become: Yes
    - role: tcharl.fail2ban
    - role: tcharl.ansible_routing
#    - role: robertdebock.bootstrap
      # TODO should run, but I'm unable to start it again. Comment it if you're not able to, but it can have side effect
#      become: Yes
#      become_method: sudo
#      become_user: root

- name: install freeipa roles & configure users
  hosts:
    - ipaservers
  roles:
    - role: tcharl.freeipa_server
    - role: tcharl.ansible_users

- name: Declare dns & reverse dns for each machine
  hosts:
    - ipaclients
    - ipaservers
  roles:
    - role: tcharl.ansible_nameserver

- name: install freeipa roles
  hosts:
    - ipaclients
  roles:
    - role: tcharl.ansible_securehost

- name: configure datastore nfs enpoints
  hosts:
    - datastore
  roles:
    - role: tcharl.ansible_volumes
    - role: tcharl.nfs_server

- name: configure reverse prereq # Execute master and nodes at the same time: one fact is created by the master and reused by nodes
  hosts: # use this order: master should be created before node
    - reverse_proxy
  roles:
    - role: tcharl.ansible_containerization
    - role: tcharl.reverse_proxy

- name: configure nfs mountpoints # Execute master and nodes at the same time: one fact is created by the master and reused by nodes
  hosts: # use this order: master should be created before node
    - kube_node
  roles:
    - role: tcharl.nfs_client

- name: configure containerization prereq # Execute master and nodes at the same time: one fact is created by the master and reused by nodes
  hosts: # use this order: master should be created before node
    - kube_master
    - kube_node
  roles:
    - role: geerlingguy.containerd
  become: Yes

- name: configure kubernetes prereq # Execute master and nodes at the same time: one fact is created by the master and reused by nodes
  hosts:
    - kube_master
    - kube_node
  vars:
    swap_file_state: absent
  roles:
    - role: geerlingguy.swap
  become: Yes

- name: configure kubernetes master # Execute master and nodes at the same time: one fact is created by the master and reused by nodes
  hosts: # use this order: master should be created before node
   - kube_master
   - kube_node
  roles:
    - role: tcharl.ansible_orchestration

- name: configure helm on kubernetes master # Execute master and nodes at the same time: one fact is created by the master and reused by nodes
  hosts: # use this order: master should be created before node
   - kube_master
  roles:
    - role: tcharl.ansible_orchestration_cli

- name: configure certmanager # Execute master and nodes at the same time: one fact is created by the master and reused by nodes
  hosts: # use this order: master should be created before node
   - kube_master
   - ipaservers
  roles:
    - role: tcharl.kube_certmanager

- name: configure service mesh # Execute master and nodes at the same time: one fact is created by the master and reused by nodes
  hosts: # use this order: master should be created before node
   - kube_master
  roles:
    - role: tcharl.servicemesh


- name: configure kubernetes master # Execute master and nodes at the same time: one fact is created by the master and reused by nodes
  hosts: # use this order: master should be created before node
   - kube_node
  roles:
    - role: tcharl.orchestration_csi
...
