---
- name: configure datastore nfs enpoints
  hosts:
    - datastore
  roles:
    - role: tcharl.ansible_volumes

# - name: configure reverse proxy
#  hosts: reverse_proxy
#  roles:
#    - role: ansible-routing
