---
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.kubernetes
    source: https://galaxy.ansible.com

  - name: geerlingguy.swap
    source: https://galaxy.ansible.com

  - name: geerlingguy.docker
    source: https://galaxy.ansible.com

  - name: tcharl.ansible_containerization
    source: https://galaxy.ansible.com

  - name: tcharl.ansible_volumes
    source: https://galaxy.ansible.com

  - name: mrlesmithjr.manage-lvm
    source: https://galaxy.ansible.com

  - name: tcharl.ansible_hostname
    source: https://galaxy.ansible.com

  - name: tcharl.ansible_nameserver
    source: https://galaxy.ansible.com

  - name: robertdebock.bootstrap
    source: https://galaxy.ansible.com

  - name: robertdebock.core_dependencies
    source: https://galaxy.ansible.com

  - name: robertdebock.reboot
    source: https://galaxy.ansible.com

  - name: tcharl.ansible_routing
    source: https://galaxy.ansible.com

  - name: robertdebock.fail2ban
    source: https://galaxy.ansible.com

  - name: robertdebock.epel
    source: https://galaxy.ansible.com

  - name: tcharl.ansible_securehost
    source: https://galaxy.ansible.com

  - name: geerlingguy.ntp
    source: https://galaxy.ansible.com

  - name: tcharl.ansible_orchestration
    source: https://galaxy.ansible.com
