---
serviceAccount:
  name: "keycloak-sc"
podSecurityContext:
  {
    "fsGroup":534000007
  }
securityContext:
  {
    "runAsNonRoot":true,"runAsUser":534000007
  }
service:
  type: LoabBalancer
ingress:
  enabled: True
  rules:
    - host: {{ .Release.Name }}.keycloak.internal.osgiliath.net
pgchecker:
  securityContext:
    {
      "allowPrivilegeEscalation":false,
      "runAsGroup":534000007,
      "runAsNonRoot":true,
      "runAsUser":534000007
    }
postgresql:
  postgresqlPassword: ThisIsATestPasswordToReplaceBySecretAndItIsAStory