---

- name: install firewalld
  become: "{{ firewalld_become }}"
  package:
    name: firewalld
    state: present

- name: enable and start firewalld
  become: "{{ firewalld_become }}"
  service:
    name: firewalld
    state: started
    enabled: true
