---
# This is a basic workflow to help you get started with Actions
name: Molecule

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
    branches:
      - master
      - tags/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install lint prerequisite
        run: |
          sudo apt-get update
          sudo apt -y install python3-setuptools ansible-lint vagrant

      - name: Install molecule
        run: |
          sudo apt update
          sudo apt -y install python3-setuptools python3 python3-pip
          sudo pip3 install wheel
          sudo pip3 install molecule testinfra yamllint ansible-lint flake8 molecule-vagrant

      - name: molecule lint
        run: |
          molecule lint

  molecule:

    runs-on: ubuntu-latest
    if: "false"
      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: refresh repositories
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update

      - name: install virtualization stack
        run: |
          sudo apt -y install bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev

      - name: install vagrant
        env:
          VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT: 1
        run: |
          wget https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.deb
          sudo apt -y install ./vagrant_2.2.7_x86_64.deb
          sudo vagrant plugin install vagrant-persistent-storage
          sudo vagrant plugin install vagrant-libvirt

      - name: Install molecule
        run: |
          sudo apt-get -y purge python3-openssl && sudo apt-get -y autoremove
          sudo apt-get update && sudo apt-get install -y ca-certificates curl gcc iproute2 python3 python3-dev sudo
          curl -skL https://bootstrap.pypa.io/get-pip.py | sudo -H python3
          sudo pip3 install wheel
          sudo pip3 install netaddr python-vagrant yamllint testinfra flake8
          sudo pip3 install ansible ansible-lint
          sudo pip3 install -I molecule molecule-vagrant

      - name: test molecule on vm
        run: |
          PATH=/home/runner/.local/bin:$PATH bash -c 'sudo molecule test --scenario-name kvm'