# This is a basic workflow to help you get started with Actions

name: Publish documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # generate the site
    - name: Run site generation
      run: ./mvnw site

    # stage the site
    - name: Staging site
      run: ./mvnw site:stage

    - name: configure ssh
      env:
        sshkey: ${{ secrets.githubrsa }}
      run: |
        which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
        eval `ssh-agent`
        mkdir -p ~/.ssh/
        rm -rf ~/.ssh/id_rsa
        echo $sshkey | sed -r 's/\\n/\n/g' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        rm -rf ~/.ssh/id_rsa.pub
        echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDEhPPsErLx70NFO8az3ZQZ8xVG95eDF1DAuUEo13muMSLWLsaZi6RSsgtlJLvH2wxcWPPma9dZAKZCopR1g7XWPkntY62lhKXCAxJBTWoN/o738/PgHS81NoPEudC/NUKkJqWrlkQrZnYidQd/cCvaTSJjwMwR6Mmd1Ua4MRIWp2AanQODDrnSN64QdrgoZ8nS31Zkl0j95/4/HGNkZdlrabINyjxhXKNkQ+C6U4JXRtDvpOE4WR98IccLrQdVNPLzms099NU1Mpfd5c4UjET57IwhLAntM2oscCQonQmpBkgxtlRvLMTP5VMD/YEHINzEC1N/gZ4IZ4L2Gnov0vLc0jaDOE6uXU8UUr6AhZSWpzjtK/CqOkTr2gQMokcE7oVgBeVo/qK4hy3Ews9Dx5Jwsde+EJmOaPSA5/qc/TiLI6emQV3mnGBUZcBlC8gqpBIblpJqo1nRtH7aFgJW2hRqfZic9z645+1SQkaY8ImMGRp/SfkZaiIUeparjuWD3HWTm7oBeFBQ4aX/S1vtg04mNZnluqoyuziFWK/8BzbkWVgezHsWNBuzFItPvlE0yp2eNLaJ/5U7vsOKfrdHyw5dur12ZmtI6SBiu4l3BULyvI61xcd+Lf6PzjYSi2DnGCLTxWnlCkeFk/Zr0on9lRUtDkX01kd8lwB9J993jP+Yvw== ci@github.com" > ~/.ssh/id_rsa.pub
        ssh-add ~/.ssh/id_rsa
        rm -rf ~/.ssh/known_hosts
        ssh-keyscan -t rsa github.com > ~/.ssh/known_hosts
        git remote remove origin
        git remote add origin git@github.com:OsgiliathEnterprise/platform.git
        git fetch --all
        git checkout master || git checkout -b master
        git pull origin master
        git push origin --delete gh-pages || true
        git checkout -b gh-pages
        git push origin gh-pages
        git checkout master
        git branch -D gh-pages
        git config --global user.email "ci@osgiliath.net"
        git config --global user.name "Continuous integration"

      # publish the site
    - name: Publish site on branch
      run: ./mvnw scm-publish:publish-scm

    - name: tear down
      run: |
        ~/.ssh/id_rsa*